distinguish practical kana ranges from strict Unicode kana ranges
fosskers/rs-kanji pull request #7
Opened 2022-03-12 18:48 UTC by makemeunsee

Hello,

In case PRs are welcome, here's one as I realized that the `is_hiragana` and `is_katakana` functions can give surprising results, e.g.
```
assert!(kanji::is_katakana('・'), false);
assert!(kanji::is_hiragana('ゟ'), false);
assert!(kanji::is_hiragana(' ゚'), false);
```

The reality is even more complex, as more kana-like signs exist out there, see [1](https://www.unicode.org/charts/PDF/U1B130.pdf) [2](https://www.unicode.org/charts/PDF/U31F0.pdf) [3](https://www.unicode.org/charts/PDF/UFF00.pdf), I can gladly attempt to cover these sub-ranges too if there's an interest.

Please let me know if you have any suggestion about the code or the PR in general.

2022-03-18 18:07 UTC, fosskers requested changes

2022-03-18 18:07 UTC, fosskers commented on src/lib.rs
> +/// Is a given `char` betwen あ and ゖ?
Which け is that?

2022-03-18 18:07 UTC, fosskers commented on src/lib.rs
> +/// including ponctuation, marks and a digraph
```suggestion
/// including punctuation, marks and a digraph
```

2022-03-18 18:07 UTC, fosskers commented on src/lib.rs
> +/// including marks and a digraph
```suggestion
/// including marks and a digraph.
```

2022-03-18 18:08 UTC, fosskers commented
I remember going through those docs when I was initially determining the ranges. So what's reasonable here? Would it be better to have  the original and `extended` variants just be the same thing, and extend the original ranges?

2022-03-19 11:35 UTC, makemeunsee commented on src/lib.rs
> +/// Is a given `char` betwen あ and ゖ?
small ke, ie `'\u{3096}'`, the last code in the range. I'm wondering if the doc could be usefully extended, but the code is really straightforward and the specs referenced already.

2022-03-19 11:49 UTC, makemeunsee commented
I doubt there's a single good answer, what one understands by `hiragana` (or any characters set) will depend on their context. Just sticking to the previous behavior is a reasonable stance, if only so existing users dont get surprised themselves by a new version of the library.

I dont have a strong opinion, maybe just extending the doc to make it explicit it's not just the range `[あ-ん]`

2022-03-19 15:17 UTC, fosskers commented on src/lib.rs
> +/// Is a given `char` betwen あ and ゖ?
```suggestion
/// Is a given `char` betwen あ and ゖ (small け)?
```

2022-03-19 15:57 UTC, merged

2022-03-19 15:57 UTC, fosskers commented
Thanks for this.

2022-03-19 16:07 UTC, fosskers commented
I'm fusing them after all and not bothering with the `*_extended` variants. Making a release soon.

2022-03-19 23:14 UTC, makemeunsee commented
great, glad it's been useful!